### ISSUE TITLE
bug: markdown rewrite replaces own-site URLs with internal docker reference

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/shared-sites#15]
![image](https://github.com/keymanapp/shared-sites/assets/4498365/974a857a-7c46-47cd-8655-df81b58d1cbc)

from:

```md
The .kvks file contained a virtual key that was not supported by
Keyman. Remove this virtual key from the .kvks file.

Supported virtual keys: https://help.keyman.com/developer/language/guide/virtual-keys#common-virtual-key-codes
```

(Note: the snippet in question is not yet live)

**Comment by mcdurdin** [comment]
This may only happen on development mode, doesn't seem to be happening on production.

**Comment by darcywong00** [comment]
I think it's from this block (See also #6)

https://github.com/keymanapp/shared-sites/blob/88d06fc2fe56ae7cbec009a14aeff7dc37fbaa3e/_common/KeymanHosts.php#L142-L151

Maybe we don't replace if host is self?

**Comment by mcdurdin** [comment]
I think we should rely on website-local-proxy being running. We already do that for s.keyman.com in that code snippet. Then we shouldn't need to expose the host.docker.internal addresses at all?
